[[plugins]]
# plugin manager
repo = 'Shougo/dein.vim'

[[plugins]]
# status bar theme
repo = 'itchyny/lightline.vim'

[[plugins]]
# For Nim
repo = 'zah/nim.vim'

[[plugins]]
# Quick run
repo = 'thinca/vim-quickrun'

[[plugins]]
# Syntax checker
repo = 'w0rp/ale'

[[plugins]]
# Git supports
repo = 'tpope/vim-fugitive'
repo = 'airblade/vim-gitgutter'

[[plugins]]
# Color scheme
repo = 'jonathanfilip/vim-lucius'
repo = 'gosukiwi/vim-atom-dark'

[[plugins]]
# smooth scroll
repo = 'yuttie/comfortable-motion.vim'

[[plugins]]
# Display end of line white space
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
# Auto close paren
repo = 'cohama/lexima.vim'

[[plugins]]
# JavaScript syntax syntax highlighting
repo = 'othree/yajs.vim'

[[plugins]]
# Rainbow parentheses
repo = 'luochen1990/rainbow'

[[plugins]]
# Highlighting same words
repo = 'RRethy/vim-illuminate'

[[plugins]]
# asynchronous execution library
repo = 'Shougo/vimproc.vim'
build = 'make'
